<a href="https://colab.research.google.com/github/dheva85/Python-ML/blob/main/Numpy_Tutorial_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of NumPy Arrays:
1. Allows several Mathematical Operations
2. Faster Operations

In [1]:
import numpy as np


List vs NumPy - Time Taken

In [3]:
from time import process_time

Time taken by a list

In [15]:
python_list = [i for i in range(1000000)]

start_time = process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.09377468599999972


In [16]:
np_array = np.array([i for i in range(1000000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)


0.001475569000000121


NumPy Arrays

In [18]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [19]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [23]:
# creating a 1 dim array
a =  np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [21]:
a.shape

(4,)

In [24]:
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
b.shape


(2, 4)

In [28]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in NumPy Arrays

In [29]:
# create a numpy array of zeros(0)
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
# create a numpy array of ones(1)
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
#array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [38]:
#create an identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
#create an numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.51506633 0.73868224 0.86440518 0.98720176]
 [0.97001112 0.81649945 0.55521789 0.69155546]
 [0.44384345 0.43731966 0.19432555 0.5007906 ]]


In [45]:
# create a random array with integers within specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[51 51 61 34 75]
 [62 12 90 90 74]
 [83 29 94 99 24]]


In [50]:
# create an array evenly spaced values  --> specifying number and range of values
d = np.linspace(10,30,5) # number of values
print(d)

[10. 15. 20. 25. 30.]


In [53]:
# array of evenly spaced values ---> specifying step
e = np.arange(10,30,5) #step size
print(e)

[10 15 20 25]


In [55]:
# convert lsit to a numpy array
list2= [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analsysing a numpy array

In [63]:
c = np.random.randint(10,90,(5,5))
print(c)

[[25 46 10 62 82]
 [64 35 43 26 78]
 [45 45 53 36 78]
 [10 21 42 48 57]
 [39 41 22 79 18]]


In [64]:
# array dimension
print(c.shape)

(5, 5)


In [65]:
# number of dimension
print(c.ndim)

2


In [66]:
# number of elements in an array
print(c.size)

25


In [67]:
# check data type of the values in array
print(c.dtype)

int64


Mathematical Operations on NumPy Array

In [69]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)  #concatenate 2 list / join 2 list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [71]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a+b)

[ 7  9 11 13 15]


In [76]:
c = np.random.randint(0,10,(3,3))
d = np.random.randint(10,20,(3,3))
print(c+d)
print(c-d)
print(c*d)
print(c/d)

[[13 20 19]
 [22 21 18]
 [18 15 28]]
[[-13  -6  -7]
 [ -4  -5 -18]
 [-18  -5 -10]]
[[  0  91  78]
 [117 104   0]
 [  0  50 171]]
[[0.         0.53846154 0.46153846]
 [0.69230769 0.61538462 0.        ]
 [0.         0.5        0.47368421]]


In [78]:
print(np.add(c,d))

[[13 20 19]
 [22 21 18]
 [18 15 28]]


In [79]:
print(np.subtract(c,d))

[[-13  -6  -7]
 [ -4  -5 -18]
 [-18  -5 -10]]


In [80]:
print(np.multiply(a,b))

[ 6 14 24 36 50]


In [81]:
print(np.divide(c,d))

[[0.         0.53846154 0.46153846]
 [0.69230769 0.61538462 0.        ]
 [0.         0.5        0.47368421]]


Array Manipulation

In [82]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 8 4]
 [7 2 8]]
(2, 3)


In [85]:
# create transpose of this matrix
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 7]
 [8 2]
 [4 8]]
(3, 2)


In [86]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 9 2]
 [6 6 2]]
(2, 3)


In [88]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[1 6]
 [9 6]
 [2 2]]
(3, 2)


In [90]:
# reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 1 9]
 [9 7 5]]
(2, 3)


In [92]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[3 1]
 [9 9]
 [7 5]]
(3, 2)
